### ISSUE TITLE
What's the relationship between this repo and explore.ggcr.dev?

### ISSUE THREAD

**Issue by zhangyoufu** [jonjohnsonjr/dagdotdev#22]
I found that https://explore.ggcr.dev/ and https://oci.dag.dev/ look similar. And I cannot find public information about who operates ggcr.dev. Can you share any information?

**Comment by jonjohnsonjr** [comment]
The `explore.ggcr.dev` site is a frozen-in-time version of `oci.dag.dev` that I had operated while working at Google. I own the domain, but it's effectively a ghost ship that's just running indefinitely on Cloud Run. Other than the domain name, it costs me nothing to run, so I haven't bothered shutting it down. It also serves as kind of a canary for me to know if someone decided to turn it off 😄

**Comment by zhangyoufu** [comment]
Thanks for sharing.
