### ISSUE TITLE
unexpected EOF for some zstd image

### ISSUE THREAD

**Issue by zhangyoufu** [jonjohnsonjr/dagdotdev#37]
https://oci.dag.dev/layers/youfu/zstd@sha256:94780ce8d6871b2bdcb66b3db56e1abe5cc51c0040622a7c97b2635432c949ed/

> failed: createIndex: TODO: don&#39;t return this error: unexpected EOF

`crane export youfu/zstd` works well on this image.

**Comment by jonjohnsonjr** [comment]
Thanks for letting me know, should be fixed now 👍
